# Generated by Django 5.0.1 on 2025-03-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_options_remove_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(default='Cash'),
        ),
    ]
