# Generated by Django 5.0.1 on 2025-12-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='color',
            field=models.CharField(default='lightGreen', max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plan',
            name='icon',
            field=models.CharField(default='Baby', max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
