version: "3.9"

services:

  es:
    image: elasticsearch:7.17.16
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - reverseproxy_nw
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
  api: &api
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    depends_on:
      - postgres
      - redis
      - es
    command: /start
    image: letaskono_api
    networks:
      - reverseproxy_nw

  postgres:
    build:
      context: .
      dockerfile: ./docker/production/postgres/Dockerfile
    image: letaskono_api_database
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    networks:
      - reverseproxy_nw

  redis:
    image: redis:7-alpine
    networks:
      - reverseproxy_nw

  celery_worker:
    <<: *api
    image: letaskono_api_celery_worker
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    command: /start-celeryworker
    networks:
      - reverseproxy_nw

  flower:
    <<: *api
    image: letaskono_api_flower
    command: /start-flower
    ports:
      - "5555:5555"
    networks:
      - reverseproxy_nw

networks:
    reverseproxy_nw:
        external: true

volumes:
  static_volume: { }
  media_volume: { }
  production_postgres_data: { }
  production_postgres_data_backups: { }
  flower_data: { }
