version: "3.9"

services:
  es:
    image: elasticsearch:7.17.16
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app_network

  celery_worker:
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    env_file:
      - ./.envs/.production/.django
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - ./docker/production/django/celery/worker/start:/start-celeryworker
    command: /start-celeryworker
    networks:
      - app_network

  flower:
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    env_file:
      - ./.envs/.production/.django
    volumes:
      - ./docker/production/django/celery/flower/start:/start-flower
    command: /start-flower
    ports:
      - "5555:5555"
    networks:
      - app_network

  django:
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    env_file:
      - ./.envs/.production/.django
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8002:8000"
    networks:
      - app_network
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000

networks:
  app_network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
