version: "3.9"
#RUN THIS COMMAND TO RUN PORTAINER AFTER RUNNING NGINX-PROXY-MANAGER IMAGE
#sudo docker run -d -p 8000:8000 --network reverseproxy_nw --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  default:
    name: reverseproxy_nw
    external: true