version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:z
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.local/.django
    depends_on:
      - redis
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - app-network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
    depends_on:
      - redis
    command: celery -A main worker --loglevel=info
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    networks:
      - app-network

networks:
  app-network:
    driver: bridge