version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:z
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.local/.django
    depends_on:
      - redis
    command: /start
    networks:
      - app-network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
    depends_on:
      - redis
    command: celery -A your_project_name worker --loglevel=info
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
