# Generated by Django 5.0.1 on 2024-03-15 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="examjourney",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="questions.language"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="questions.level"
            ),
        ),
        migrations.AddField(
            model_name="examjourney",
            name="questions",
            field=models.ManyToManyField(to="questions.question"),
        ),
        migrations.AddField(
            model_name="question",
            name="answers",
            field=models.ManyToManyField(
                related_name="questions", to="questions.questionanswer"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="questions.questionanswer",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="specificity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="questions.specificity"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="subjects",
            field=models.ManyToManyField(to="questions.subject"),
        ),
        migrations.AddField(
            model_name="question",
            name="systems",
            field=models.ManyToManyField(to="questions.system"),
        ),
        migrations.AddField(
            model_name="question",
            name="topics",
            field=models.ManyToManyField(to="questions.topic"),
        ),
        migrations.AddField(
            model_name="question",
            name="years",
            field=models.ManyToManyField(to="questions.year"),
        ),
    ]
