# Generated by Django 5.0.1 on 2025-03-22 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="examjourney",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="questions.language"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="questions.level"
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="questions.question"
            ),
        ),
        migrations.AddField(
            model_name="examjourney",
            name="questions",
            field=models.ManyToManyField(to="questions.question"),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="questions.question",
            ),
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="q_answers",
                to="questions.question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correct_questions",
                to="questions.questionanswer",
            ),
        ),
        migrations.AddField(
            model_name="answerimage",
            name="question_answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="questions.questionanswer",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="questions.question"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="specificity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="questions.specificity"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="subjects",
            field=models.ManyToManyField(to="questions.subject"),
        ),
        migrations.AddField(
            model_name="question",
            name="systems",
            field=models.ManyToManyField(to="questions.system"),
        ),
        migrations.AddField(
            model_name="tempquestion",
            name="excel_upload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="temp_questions",
                to="questions.excelupload",
            ),
        ),
        migrations.AddField(
            model_name="tempanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="temp_answers",
                to="questions.tempquestion",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="topics",
            field=models.ManyToManyField(to="questions.topic"),
        ),
        migrations.AddField(
            model_name="userquestionstatus",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="questions.question"
            ),
        ),
        migrations.AddField(
            model_name="userquestionstatus",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="years",
            field=models.ManyToManyField(to="questions.year"),
        ),
    ]
