# Generated by Django 5.0.1 on 2024-10-03 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_remove_question_answers_questionanswer_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correct_questions",
                to="questions.questionanswer",
            ),
        ),
    ]
