# Generated by Django 5.0.1 on 2024-06-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="hint",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="question",
            name="video_hint",
            field=models.URLField(blank=True, default=""),
        ),
    ]
