# Generated by Django 5.0.1 on 2025-03-28 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamJourneyQuestionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('exam_journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_orders', to='questions.examjourney')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('exam_journey', 'position')},
            },
        ),
    ]
