# Generated by Django 5.0.1 on 2025-03-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_examjourneyquestionorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamJourneyQuestionOrder',
        ),
    ]
