# Generated by Django 5.0.1 on 2025-03-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_delete_examjourneyquestionorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='examjourney',
            name='question_order',
            field=models.JSONField(default=list),
        ),
    ]
