# Generated by Django 5.0.1 on 2025-04-21 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0005_examjourney_question_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestionstatus",
            name="exam_journey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="questions.examjourney",
            ),
        ),
    ]
