# Generated by Django 5.0.1 on 2025-07-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0006_userquestionstatus_exam_journey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="subjects",
            field=models.ManyToManyField(blank=True, to="questions.subject"),
        ),
        migrations.AlterField(
            model_name="question",
            name="systems",
            field=models.ManyToManyField(blank=True, to="questions.system"),
        ),
        migrations.AlterField(
            model_name="question",
            name="topics",
            field=models.ManyToManyField(blank=True, to="questions.topic"),
        ),
    ]
