# Generated by Django 5.0.1 on 2025-01-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_excelupload_remove_tempquestion_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelupload',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
