# Generated by Django 5.0.1 on 2025-01-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_question_hint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['year']},
        ),
    ]
