# Generated by Django 5.0.1 on 2025-02-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0010_alter_year_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faq", models.CharField(max_length=255, verbose_name="faq")),
                ("answer", models.TextField(verbose_name="Answer")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Home Page Video URL",
                    ),
                ),
            ],
        ),
    ]
