# Generated by Django 5.0.1 on 2025-03-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0012_alter_homepage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="answer_uk",
            field=models.TextField(default="", verbose_name="Answer_uk"),
        ),
        migrations.AddField(
            model_name="faq",
            name="faq_uk",
            field=models.CharField(default="", max_length=255, verbose_name="faq_uk"),
        ),
    ]
