# Generated by Django 5.0.1 on 2025-02-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_activationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_activation_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
