# Generated by Django 5.0.1 on 2024-12-23 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='answer_text',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.CreateModel(
            name='AnswerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='answer_images/')),
                ('question_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='questions.questionanswer')),
            ],
        ),
    ]
