# Generated by Django 5.0.1 on 2025-01-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_excelupload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answer_images/'),
        ),
        migrations.AddField(
            model_name='tempanswer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='temp_answer_images/'),
        ),
    ]
