# Generated by Django 5.0.1 on 2025-01-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_questionanswer_image_tempanswer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, default=''),
        ),
    ]
