# Generated by Django 5.0.1 on 2025-03-01 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0011_faq_homepage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={
                "verbose_name": "Home Video",
                "verbose_name_plural": "Home Video Settings",
            },
        ),
    ]
