# Generated by Django 5.0.1 on 2024-03-15 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="favoritelist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="favoriteitem",
            name="favorite_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.favoritelist"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="favorites_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.favoritelist",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="follows",
            field=models.ManyToManyField(
                blank=True, related_name="followed_by", to="profiles.profile"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
