# Generated by Django 5.0.1 on 2024-06-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="about_me",
        ),
        migrations.AddField(
            model_name="profile",
            name="university",
            field=models.TextField(
                blank=True,
                default="Your University",
                max_length=180,
                null=True,
                verbose_name="university",
            ),
        ),
    ]
