# Generated by Django 5.0.1 on 2025-02-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_email_activation_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_url",
                    models.CharField(help_text="URL of the video", max_length=255),
                ),
                ("description", models.TextField(help_text="Description of the video")),
            ],
            options={
                "verbose_name": "Video Configuration",
                "verbose_name_plural": "Video Configurations",
            },
        ),
    ]
